### ISSUE TITLE
How to Donate/Sponsor the project?

### ISSUE THREAD

**Issue by freakyalgo** [deptagency/algomart#406]
## Overview

I own an NFT Project called [AlgoFreaks ](https://www.nftexplorer.app/collection/algofreaks ) that makes quarterly donations to Algorand-related Open-Source projects and it turns out our first donation goes to you.
Unfortunately I cannot find any way to either send ALGO or actual money to support the project.

I would appreciate if you could either turn on the Sponsoring section for your repo or provide the best way to donate to the project in your README.

**Comment by brandonaaskov** [comment]
We definitely appreciate the sentiment, however, it just wouldn't be right to accept donations. The majority of the team that's currently maintaining the repo works at [DEPT](https://www.deptagency.com/en-us/). While anyone can use Algomart because it's open source, it has helped us win some customers as well. And since it's being use for commercial purposes, it simply doesn't seem ethical to take donations.

We're also not looking for any sponsorships at the moment, largely so that we can make the right decisions for the product that aren't influenced by third-parties. There are a lot of great projects in the Algorand ecosystem, however, and poking through [the /r/AlgorandOfficial subreddit](https://www.reddit.com/r/AlgorandOfficial/) will turn up a lot of interesting work. Thank you though :)
