### ISSUE TITLE
Can't see image preview for the NFT template.

### ISSUE THREAD

**Issue by BeyondSpace609520** [deptagency/algomart#58]
## Overview

I can't see the image preview for the NFT template.

## To reproduce

Go to 'http://18.223.54.34:3000/releases', the image is just blank.
Go to 'http://18.223.54.34:3000/releases/11111', can see the image.

The image URI of the image is not correct.

## Screenshots

![image](https://user-images.githubusercontent.com/56730274/140649490-23bb581b-4503-41b0-bc5e-cb3ca920dcba.png)

## Desktop (if applicable):

- ubuntu 20

**Comment by smonn** [comment]
Hey @BeyondSpace609520, most likely this is due to the files not [being made public in the CMS](https://github.com/deptagency/algomart/tree/main/apps/cms#1-make-files-publicly-viewable), or the [`CMS_URL`](https://github.com/deptagency/algomart/blob/main/services/api/.env.example#L17) not being a publicly accessible one. Going by your second screenshot, my guess is on the latter.

**Comment by smonn** [comment]
Still working through some issues running AlgoMart via `docker-compose up`, so for now I recommend running this via `npm run dev` directly instead.

**Comment by BeyondSpace609520** [comment]
Thanks for your help @smonn. I will close this issue.
