### ISSUE TITLE
Defer sending initial funds until first NFT transfer

### ISSUE THREAD

**Issue by smonn** [deptagency/algomart#62]
## Overview

To avoid locking up Algos in unused accounts (0.1 Algo per account), we should defer sending the initial amount until a user acquires their first NFT. This will ensure we keep funds in the funding wallet for as long as possible and is great for storefronts that will mostly rely on auctions where the NFT volume is relatively low.

**Comment by brandonaaskov** [comment]
@afraser and @dallashuggins this is applicable to SPIN's site for Decipher since we'll only be doing the auction model for a single item.

**Comment by kevlarr** [comment]
This will also make user sign-up more streamlined and less error-prone. Right now, if the funding account is empty *or* if the request to the Algo node fails (wrong token, or service is momentarily unavailable for whatever reason, etc) then account creation fails in the API after it's already succeeded in Firebase. In that case, the user is authenticated in their client but calls to the API fail because their account isn't found, and there's really no way short of them clearing their local storage & cookies *and* removing their account in Firebase to let them create another account.
